README.md

Change the flutter version in README from 1.8.4 to 1.7.8+hotfix.4 to keep it consistent with the first example and also avoid confusion because 1.8.4 beta does not exist (which will cause a http error if someone copy the code as is).

change flutter version in doc

---

src/installer.ts

Adding Flutter bin to the path doesn't expose the dart SDK which many people might be interested in using. For example, `dartdoc` for documentation generation.
Currently, one might be able to call the dart SDK by `$FLUTTER_HOME/bin/cache/dart-sdk/dart`, but it would be interesting if that can be simplified to just `dart` or `dartdoc`.

might be interesting to add dart SDK to path

---

README.md

add example script which will build a windows executable and also upload it to action artifacts
Is      `  - uses: actions/setup-java@v1 ` required?
I tried this on my own repository and to my surprise it actually worked.

add example to build for windows

---

dist/index.js
src/installer.ts

Fixes #89 
Export `PUB_CACHE` if it is not configured before calling the action.
This ensures that flutter and dart use the same cache.
It also enables other tools to use this official Dart env variable.

Export PUB_CACHE if it is not in env

---

dist/index.js
src/release.ts

It seems like the previous endpoint broke a few minutes ago so here's a quick pull request that fixes the issue.

Fix the endpoint for flutter releases

---

README.md

I recently noticed that several workflows started to fail after Dependabot update.
It turns out to be a breaking change in the setup-java action. For details, see https://github.com/actions/setup-java/blob/main/docs/switching-to-v2.md.
It's good to update the instructions early before developers are caught off guard.

chore: migrate setup java in the instructions to v2

---

setup.sh

Using the $HOME folder can be problematic in some constellations on private runners.
$RUNNER_TEMP is the official environment variable for a runner specific temp folder.

Download and unzip to temp folder and not $HOME

---

.github/workflows/workflow.yml
README.md

The Flutter team is not supporting the `dev` channel anymore (ref: https://github.com/flutter/flutter/issues/94962).
This PR removes all mentions to `dev` channel in the codebase.

Remove dev channel mentions

---

.github/workflows/workflow.yml
setup.sh

Follow up for #132 
Something with the globing seems not work but not sure exactly. Now using a simple way of ensure that the target folder never exists when calling `mv` so that it behaves as a rename instead of a move into. The folder still needs to be created first so that parent folders (in case of a custom cache path) are created.
Added a .gitignore
Only run on push/pr on main branch to avoid duplicate builds and overuse of macos-runners.

Fix temp folder handling on windows

---

.github/workflows/workflow.yml
README.md
action.yml
setup.sh

feat: support to set architecture of SDK executable

---

.github/workflows/workflow.yml
README.md

https://github.com/actions/checkout#checkout-v3

Bump actions/checkout to v3

---

action.yml

Right now the `cache-key` parameter at the action level doesn't work, because the value is not propagated to the bash script.
This PR adds this missing parameter to be able to customize the cache key value.

Added missing parameter for cache-key

---

.github/workflows/workflow.yml
README.md
setup.sh

See https://github.com/subosito/flutter-action/issues/51#issuecomment-830139637

feat: Allow git ref as version in `master` channel

---

.github/workflows/workflow.yml
README.md
setup.sh

- add support for the `main` channel
- fix https://github.com/subosito/flutter-action/issues/257
- update related testing and docs

add support for the `main` channel

---

.github/workflows/workflow.yml
action.yml
setup.sh

Apple silicon is now available. 
https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/
This makes it necessary in some cases to set arm64 for the architecture option.
There is already an option (Thanks!). However, in most cases x64 is used and the option is missed. Therefore, it is likely that users with Apple silicon will not realize that they need to configure arm64.
To solve the above problem, I added a process to get the appropriate architecture from `runner-arch` if the option is not set. 
Thanks for the great tool.

Set architecture options from runner's architecture

---

README.md
action.yml
setup.sh

- Update actions/cache to v4 to suppress warnings about old node.js versions
- Allow users to set `PUB_CACHE` before invoking the action to control where the .pub-cache directory lives
- Cache the .pub-cache directory separately from the flutter installation, since the former will change often and the latter will change rarely -- this reduces the amount of cache churn / space used up in the cache until the data expires

Improvements to caching

---

action.yml
setup.sh

Currently, specifying a `pub-cache-path` like in the README doesn't do anything. This PR fixes this by adding the input. I've set up the priority like this:
1. If the environmental variable `PUB_CACHE` is specified before using the action, continue using it. 
2. If `PUB_CACHE_PATH` is specified and is not the default value, then use it.
3. Otherwise, use the defaults set by Dart as per https://dart.dev/tools/pub/environment-variables
In every case, the value will be re-exported as the environment variable by the name of `PUB_CACHE`, written to the action's output in the variable `PUB-CACHE-PATH`, and its `bin` sub-directory appended to `PATH`
resolves https://github.com/subosito/flutter-action/issues/278
resolves https://github.com/subosito/flutter-action/issues/277

fix: specify pub cache path

---

.github/workflows/workflow.yml

https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
With `macos-14`, the m1 environment (arm64 environment) is available.
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
Currently, `macos-latest` refers to `macos-12`.
After Q2 Since FY24 (April - June 2024), `macos-latest` will refer to `macos-14`.
For this reason, I have added `[macos-latest, macos-13, macos-14]` to the list to be tested; once macos-latest references macos-14, I will create a PR to change the list to `[macos-latest, macos-13]`.
This change allows us to check that flutter-action works in both intel mac and m1 mac environments.

chore: Add m1 chip macos machine

---

README.md

This is my proposal to structure it in the way that I would like to be guided:
1. choose flutter version
2. choose build target
3. add caching
---
- Adds sections: Flutter Version, Build Target, Cache
- Make bold build target names to find them more easily
- fixes #283

Restructure Documentation

---

.github/workflows/workflow.yaml
README.md
action.yaml
setup.sh

Split longer lines in action.yaml

---

.github/workflows/workflow.yaml
README.md
action.yaml

I want `dry-run` parameter for printing.

Add dry-run

---

.github/workflows/workflow.yaml
action.yaml

Fix failing tests

---

.github/workflows/workflow.yaml

Remove the macos-14 designation from matrix because macos-latest is now macos-14.
The `test_print_output` is not updated to macos-latest because the test assumes that it works on intel mac.
https://github.blog/changelog/2024-04-01-macos-14-sonoma-is-generally-available-and-the-latest-macos-runner-image/
ref: https://github.com/subosito/flutter-action/pull/281
---
Intended to be merged after https://github.com/subosito/flutter-action/pull/303. The CI fix and macos-14 removal can be done at the same time, but split because the main purpose of the PR is different.

Remove macos-14 from matrix

---

setup.sh

For some reason, Ubuntu has their latest version to [4.16.2](https://launchpad.net/~rmescandon/+archive/ubuntu/yq), and that version of yq doesn't use eval by default as it does with the newer versions.
https://mikefarah.gitbook.io/yq#notice-for-v4.x-versions-prior-to-4.18.1
Old 4.16.2:
```bash
~$ yq --version
yq (https://github.com/mikefarah/yq/) version 4.16.2
~$ yq '.environment.flutter' pubspec.yaml
Error: unknown command ".environment.flutter" for "yq"
Run 'yq --help' for usage.
~$ yq eval '.environment.flutter' pubspec.yaml 
3.24.4
```
New version
```bash
~$ yq --version
yq (https://github.com/mikefarah/yq/) version v4.44.2
~$ yq '.environment.flutter' pubspec.yaml 
3.24.4
~$ yq eval '.environment.flutter' pubspec.yaml 
3.24.4
```
One info, latest version of yq is able to be …

Support older yq versions

---

.github/workflows/workflow.yaml

Since macos-latest has been updated to arm64 machines, I splited `test_print_output` between x64 and arm64. And flutter sdk for arm64 has been provided since v3.0.0, so checked only versions after v3.0.0.
ref #303 #304

Split test cases by architecture

---

action.yaml

As mentioned in open issue #319, the `restore-keys` specified within `action.yaml` leads to some unpredictable behaviour; a `pub get` cache-miss could result in a _different_ hashed lock cache to be returned instead. In our experience, this has caused pipelines to fail, as the codebase is relying on packages which are not present in the pub cache. As @rolandmosimann recommends, I feel this behaviour should be removed, to fix this problem.
As a result, this PR removes the misleading `restore-key` on `pub get` caching, as well as the unnecessary declaration of a `restore-key` matching exactly the `key`. Let me know if you've got any questions 😄

Remove restore-keys from caching

---

action.yaml

When passing a custom `pub-cache-path` the `PUB_CACHE` env variable would still point to the default value.

Fix PUB-CACHE-PATH output different to PUB_CACHE env variable

---

README.md

The Flock repository has been moved to a [new location](https://github.com/join-the-flock/flock.git). 
This PR updates the link in the README.

Update Flock's git URL in README

---

README.md
action.yaml

The `yq` install on GitHub Windows runners is really slow. But it is only needed when `flutter-version-file` is specified. This PR makes it conditional so that it is only installed when this parameter is set.
Closes #361

perf: Only install yq on Windows if used

---

README.md

use env if it existed

---

README.md
action.yaml

This PR addresses the changes requested in #346 from earlier this year, as I also would like to be able to use this feature.
It adds 2 new outputs: CACHE-HIT and PUB-CACHE-HIT. These just pass along the `cache-hit` output from `actions/cache@v4` for the `cache-flutter` and `cache-pub` steps. These can be used for increasing workflow efficiency through steps like conditionally installing dependencies when the cache is invalid. The README is also updated with example usage to skip `melos bootstrap` if `PUB-CACHE-HIT` was not `true`.
I tested the outputs here: https://github.com/beninato8-forks/flutter-action/actions/runs/15627281250/job/44023816175
```
Cache restored successfully
Cache restored from key: flutter-linux-stable-3.27.4-x64-d8a9f9a52e5af486f80d932e838ee93861ffd863
...
Cache …
```

Add cache hit outputs
